// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"github.com/google/uuid"
)

type Sessions struct {
	ID       uuid.UUID
	UserID   uuid.UUID
	Username string
	Valid    bool
}

type Users struct {
	ID             uuid.UUID
	Username       string
	HashedPassword string
}
