// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: user.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
  username, hashed_password
) VALUES (
  $1, $2
  )
RETURNING id, username, hashed_password
`

type CreateUserParams struct {
	Username       string
	HashedPassword string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (Users, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Username, arg.HashedPassword)
	var i Users
	err := row.Scan(&i.ID, &i.Username, &i.HashedPassword)
	return i, err
}

const getUser = `-- name: GetUser :one
SELECT id, username, hashed_password FROM users
where id = $1 LIMIT 1
`

func (q *Queries) GetUser(ctx context.Context, id uuid.UUID) (Users, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var i Users
	err := row.Scan(&i.ID, &i.Username, &i.HashedPassword)
	return i, err
}
