version: "3.9"

services:
  postgres:
    container_name: memo-db
    image: postgres:16-alpine
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_PASSWORD}
    volumes:
      - memo_data:/var/lib/postgresql/data

volumes:
  memo_data:
