// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: memos.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const CreateMemo = `-- name: CreateMemo :one
INSERT INTO memos (
  content,
  user_id
) VALUES (
  $1,
  $2
)
RETURNING id
`

type CreateMemoParams struct {
	Content string    `json:"content"`
	UserID  uuid.UUID `json:"user_id"`
}

func (q *Queries) CreateMemo(ctx context.Context, arg CreateMemoParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, CreateMemo, arg.Content, arg.UserID)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const DeleteMemo = `-- name: DeleteMemo :exec
DELETE FROM memos
WHERE id = $1
`

func (q *Queries) DeleteMemo(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, DeleteMemo, id)
	return err
}

const SelectUserMemos = `-- name: SelectUserMemos :many
SELECT id, content, user_id, created_at FROM memos
WHERE user_id = $1
`

func (q *Queries) SelectUserMemos(ctx context.Context, userID uuid.UUID) ([]Memos, error) {
	rows, err := q.db.Query(ctx, SelectUserMemos, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Memos
	for rows.Next() {
		var i Memos
		if err := rows.Scan(
			&i.ID,
			&i.Content,
			&i.UserID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
