// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Likes struct {
	ID     uuid.UUID `json:"id"`
	MemoID uuid.UUID `json:"memo_id"`
}

type Memos struct {
	ID        uuid.UUID        `json:"id"`
	Content   string           `json:"content"`
	UserID    uuid.UUID        `json:"user_id"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
}

type Profiles struct {
	UserID      uuid.UUID   `json:"user_id"`
	Bannerimage pgtype.Text `json:"bannerimage"`
	Bio         pgtype.Text `json:"bio"`
}

type Sessions struct {
	ID        uuid.UUID        `json:"id"`
	UserID    uuid.UUID        `json:"user_id"`
	ExpiresAt pgtype.Timestamp `json:"expires_at"`
}

type Users struct {
	ID             uuid.UUID        `json:"id"`
	Username       pgtype.Text      `json:"username"`
	Email          string           `json:"email"`
	HashedPassword string           `json:"hashed_password"`
	CreatedAt      pgtype.Timestamp `json:"created_at"`
}
