// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: sessions.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const CreateSession = `-- name: CreateSession :one
INSERT INTO sessions (
  user_id,
  expires_at
) VALUES (
  $1,
  $2
)
RETURNING id
`

type CreateSessionParams struct {
	UserID    uuid.UUID        `json:"user_id"`
	ExpiresAt pgtype.Timestamp `json:"expires_at"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, CreateSession, arg.UserID, arg.ExpiresAt)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const DeleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions
WHERE id = $1
`

func (q *Queries) DeleteSession(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, DeleteSession, id)
	return err
}

const GetSession = `-- name: GetSession :one
SELECT
  sessions.id,
  sessions.user_id,
  sessions.expires_at,
  users.email
FROM
  sessions
  JOIN users on sessions.user_id = users.id
WHERE
  sessions.id = $1
`

type GetSessionRow struct {
	ID        uuid.UUID        `json:"id"`
	UserID    uuid.UUID        `json:"user_id"`
	ExpiresAt pgtype.Timestamp `json:"expires_at"`
	Email     string           `json:"email"`
}

func (q *Queries) GetSession(ctx context.Context, id uuid.UUID) (GetSessionRow, error) {
	row := q.db.QueryRow(ctx, GetSession, id)
	var i GetSessionRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ExpiresAt,
		&i.Email,
	)
	return i, err
}

const GetUserSessions = `-- name: GetUserSessions :many
SELECT
sessions.id,
sessions.expires_at,
users.email
FROM sessions
JOIN users ON sessions.user_id = users.id
WHERE users.id = $1
`

type GetUserSessionsRow struct {
	ID        uuid.UUID        `json:"id"`
	ExpiresAt pgtype.Timestamp `json:"expires_at"`
	Email     string           `json:"email"`
}

func (q *Queries) GetUserSessions(ctx context.Context, id uuid.UUID) ([]GetUserSessionsRow, error) {
	rows, err := q.db.Query(ctx, GetUserSessions, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserSessionsRow
	for rows.Next() {
		var i GetUserSessionsRow
		if err := rows.Scan(&i.ID, &i.ExpiresAt, &i.Email); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
