// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: sessions.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const CreateSession = `-- name: CreateSession :one
INSERT INTO sessions (
  user_id,
  expires_at
) VALUES (
  $1,
  $2
)
RETURNING id
`

type CreateSessionParams struct {
	UserID    uuid.UUID        `json:"user_id"`
	ExpiresAt pgtype.Timestamp `json:"expires_at"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, CreateSession, arg.UserID, arg.ExpiresAt)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const DeleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions
WHERE id = $1
`

func (q *Queries) DeleteSession(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, DeleteSession, id)
	return err
}

const GetSession = `-- name: GetSession :one
SELECT 
  id,
  user_id,
  expires_at
FROM
  sessions
WHERE
  id = $1
`

func (q *Queries) GetSession(ctx context.Context, id uuid.UUID) (Sessions, error) {
	row := q.db.QueryRow(ctx, GetSession, id)
	var i Sessions
	err := row.Scan(&i.ID, &i.UserID, &i.ExpiresAt)
	return i, err
}
