// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: users.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const Create = `-- name: Create :one
INSERT INTO users (
  username,
  email,
  hashed_password
) VALUES (
  $1,
  $2,
  $3
)
RETURNING id
`

type CreateParams struct {
	Username       string `json:"username"`
	Email          string `json:"email"`
	HashedPassword string `json:"hashed_password"`
}

func (q *Queries) Create(ctx context.Context, arg CreateParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, Create, arg.Username, arg.Email, arg.HashedPassword)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const SelectById = `-- name: SelectById :one
SELECT
  id,
  username,
  email,
  hashed_password,
  created_at
FROM
  users
WHERE
  id = $1
LIMIT 1
`

func (q *Queries) SelectById(ctx context.Context, id uuid.UUID) (Users, error) {
	row := q.db.QueryRow(ctx, SelectById, id)
	var i Users
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.HashedPassword,
		&i.CreatedAt,
	)
	return i, err
}
