// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: users.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const CreateUser = `-- name: CreateUser :one
INSERT INTO users (
  username,
  email,
  hashed_password
) VALUES (
  $1,
  $2,
  $3
)
RETURNING id
`

type CreateUserParams struct {
	Username       pgtype.Text `json:"username"`
	Email          string      `json:"email"`
	HashedPassword string      `json:"hashed_password"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, CreateUser, arg.Username, arg.Email, arg.HashedPassword)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const SelectUserByEmail = `-- name: SelectUserByEmail :one
SELECT
  id,
  username,
  email,
  hashed_password,
  created_at
FROM
  users
WHERE
  email = $1
LIMIT 1
`

func (q *Queries) SelectUserByEmail(ctx context.Context, email string) (Users, error) {
	row := q.db.QueryRow(ctx, SelectUserByEmail, email)
	var i Users
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.HashedPassword,
		&i.CreatedAt,
	)
	return i, err
}

const SelectUserById = `-- name: SelectUserById :one
SELECT
  id,
  username,
  email,
  hashed_password,
  created_at
FROM
  users
WHERE
  id = $1
LIMIT 1
`

func (q *Queries) SelectUserById(ctx context.Context, id uuid.UUID) (Users, error) {
	row := q.db.QueryRow(ctx, SelectUserById, id)
	var i Users
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.HashedPassword,
		&i.CreatedAt,
	)
	return i, err
}
